name: Build And Push Plugin Api

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        if: ${{ !(github.event_name == 'release' && github.event.action == 'published') }}
        run: dotnet build --no-restore

      - name: Build release
        if: ${{ github.event_name == 'release' && github.event.action == 'published' }}
        run: dotnet build /p:PublicRelease=true

      - name: Test
        run: dotnet test --no-build --verbosity normal

      - name: Pack
        run: dotnet pack --configuration Release

      - name: Push nuget.org
        if: ${{ github.event_name == 'release' && github.event.action == 'published' }}
        run: dotnet nuget push "bin/Release/*.nupkg" --api-key ${{secrets.NUGET_ORG_API_KEY}} --source https://api.nuget.org/v3/index.json
