name: Create Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x
      - name: Add nuget source
        run: dotnet nuget add source --username FlurinBruehwiler --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Joa-Launcher/index.json"
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet publish ./Joa/Joa.csproj -c Release -r win10-x64 --self-contained true
      - name: Create zip file of output
        run: zip -r win10-x64.zip ./Joa/bin/Release/net7.0/win10-x64/publish
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: src/win10-x64.zip
          draft: true
          token: ${{ secrets.GITHUB_TOKEN }}
