name: Create Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  release:
    name: Release
    strategy: 
      matrix:
        kind: ['windows']
        include:
          - kind: windows
            os: windows-latest
            target: win-x64
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./src
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x
      - name: Add nuget source
        run: dotnet nuget add source --username FlurinBruehwiler --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Joa-Launcher/index.json"
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet publish ./Joa/Joa.csproj -r $${{ matrix.target }} -c Release -o $${{ matrix.target }}
      - name: Create zip file of output
        run: zip -r ${{ matrix.target }}.zip ${{ matrix.target }}
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: src/${{ matrix.target }}.zip
          draft: true
          token: ${{ secrets.GITHUB_TOKEN }}
